package com.example.demo.model;

import javax.persistence.*;

@Entity
//@Table(
//        name="person",
//        uniqueConstraints = {
//                @UniqueConstraint(name="name_unique", columnNames="name")
//        }
//)
////name is the name of the constraint columnName is the column youre constraining on
////then dont need the unique=true in @Column
public class Person {
    //generated json will have key names corresponding to property names, json values are the property values

    //makes serial type so the id is autogenerated to be in a sequence, increment(allocation size) of 1
    @Id
    //seems like sequence generation only works for id values or have to workaround by creating separate entity
    // https://stackoverflow.com/questions/277630/hibernate-jpa-sequence-non-id
    @SequenceGenerator(
            name = "personid_sequence",
            sequenceName = "personid_sequence",
            allocationSize = 1,
            initialValue = 1
    )
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "personid_sequence")
    private Long id;

    @Column(name="name", nullable = false)
    //in case you want control over the name of your column in the database tab;e
    //updatable false means noone can update this column
    //can also do nullable=false meaning cannot be null
    //can also do columnDefinition="TEXT" to change the type of the column from varchar to TEXT
    //can also do unique=true but better if use @Table (see top of class)
    private String name;
    private Integer age;
    private String address;

    //If you want to link to another entity then can do annotations like @ManyToOne before the field declaration

    public Person() {
    }

    public Person(String name, Integer age, String address) {
        //this.id = id; //removed id in constructor since the id is backed by sequence so dont need to input
        this.name = name;
        this.age = age;
        this.address = address;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}
